// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Gs1Belu.Mpm.Upload.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TradeItem_synchronisationDates : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The discontinuedDateTime property</summary>
        public DateTimeOffset? DiscontinuedDateTime { get; set; }
        /// <summary>The lastChangeDateTime property</summary>
        public DateTimeOffset? LastChangeDateTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Gs1Belu.Mpm.Upload.Models.TradeItem_synchronisationDates"/> and sets the default values.
        /// </summary>
        public TradeItem_synchronisationDates()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Gs1Belu.Mpm.Upload.Models.TradeItem_synchronisationDates"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Gs1Belu.Mpm.Upload.Models.TradeItem_synchronisationDates CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Gs1Belu.Mpm.Upload.Models.TradeItem_synchronisationDates();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "discontinuedDateTime", n => { DiscontinuedDateTime = n.GetDateTimeOffsetValue(); } },
                { "lastChangeDateTime", n => { LastChangeDateTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("discontinuedDateTime", DiscontinuedDateTime);
            writer.WriteDateTimeOffsetValue("lastChangeDateTime", LastChangeDateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
