/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createTradeItemFromDiscriminatorValue, type ProblemDetails, type TradeItem } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /tradeitems/{gtin}
 */
export interface WithGtinItemRequestBuilder extends BaseRequestBuilder<WithGtinItemRequestBuilder> {
    /**
     * Retrieve a single trade item identified by its GTIN.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TradeItem>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TradeItem | undefined>;
    /**
     * Retrieve a single trade item identified by its GTIN.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithGtinItemRequestBuilderUriTemplate = "{+baseurl}/tradeitems/{gtin}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithGtinItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithGtinItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTradeItemFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
